// swift-tools-version:5.9
//
// Auto-generated by ios/scripts/publish-to-release-repo.sh from
// ios/templates/Package.swift.in — do not hand-edit; rerun the publish
// script to bump the version / checksum.
//
// TTSignal is split into two SwiftPM targets:
//
//   - TTSignalCore  : binary xcframework (xquic + boringssl + Apple bridge,
//                     compiled C++/Obj-C++). Hosted as a release asset on
//                     GitHub Releases because git is a poor fit for a
//                     ~22 MB native blob that changes every build day.
//   - TTSignal      : Swift wrapper distributed as source. Lives in
//                     Sources/TTSignal/ and is mirrored from the upstream
//                     ttsignal repo's src/swift/ on every release. Source
//                     distribution avoids Swift module-stability lock-in,
//                     keeps the artifact small, and lets users step into
//                     the wrapper code in Xcode.

import PackageDescription

let package = Package(
    name: "TTSignal",
    platforms: [.iOS(.v13)],
    products: [
        .library(name: "TTSignal", targets: ["TTSignal"]),
    ],
    targets: [
        .binaryTarget(
            name: "TTSignalCore",
            url: "https://github.com/3th1UOYgUtJkurSZ/ttsignal-xcframework/releases/download/1.0.20260430/ttsignal-swift.zip",
            checksum: "716868dcb8f86280a69909dcba6673150f5876ef2a142750b9ab341c86e0c460"
        ),
        .target(
            name: "TTSignal",
            dependencies: ["TTSignalCore"],
            path: "Sources/TTSignal"
        ),
    ]
)
